### ISSUE TITLE
problem while this step in installation "PCP Grafana datasource installation"

### ISSUE THREAD

**Issue by ShivamJ2047** [performancecopilot/pcp-grafana-datasource#1]
In this step "symlink the dist directory into the grafana plugins directory: ln -sf $PWD/dist /var/lib/grafana/data/plugins/pcp"
instead of "/var/lib/grafana/data/plugins/pcp" .I think it should be "/var/lib/grafana/plugins/pcp".
that's how it worked on my system.

**Comment by kamolsrisan** [comment]
good

**Comment by goodwinos** [comment]
yes that is correct
